// Code generated by go-bindata. (@generated) DO NOT EDIT.
// sources:
// templates/tmuxp-config-template.go
// templates/tmuxp-config.yaml
package templates

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _templatesTmuxpConfigTemplateGo = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x01\x00\x00\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00")

func templatesTmuxpConfigTemplateGoBytes() ([]byte, error) {
	return bindataRead(
		_templatesTmuxpConfigTemplateGo,
		"templates/tmuxp-config-template.go",
	)
}

func templatesTmuxpConfigTemplateGo() (*asset, error) {
	bytes, err := templatesTmuxpConfigTemplateGoBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/tmuxp-config-template.go", size: 0, mode: os.FileMode(420), modTime: time.Unix(1540657351, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _templatesTmuxpConfigYaml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x2c\xce\xcf\x8a\x83\x30\x10\x06\xf0\x7b\x9e\xe2\x3b\x78\x5c\x7d\x80\xc0\x5e\x56\xdc\x65\x11\xec\xa1\xf4\x54\x4a\x99\xe2\x28\xa1\x3a\x29\xc6\x3f\x2d\x21\xef\x5e\xd2\x78\x9d\xf9\x7d\xdf\x0c\xcb\x6a\x26\x2b\x23\xcb\xac\x15\x50\x9f\x7e\xaa\xf2\xd0\xfc\xfe\xff\x69\x78\x8f\xa2\x5e\x6e\x5c\x5a\xe9\x4c\x8f\x3c\x04\xe5\x7d\x8e\x89\xa4\x67\x64\x77\x7e\x7d\x21\x5b\x69\x58\x18\xfa\x1b\x45\xf5\x9c\x27\xaa\x64\x75\x08\x41\x21\x86\x23\x41\x08\x9f\xa2\x1d\xa6\x0e\xb0\xb4\x51\x29\xc7\xce\x19\x2b\x57\xa1\x91\xd3\xbd\x63\x9a\x34\x34\x72\x14\x9b\x91\xd6\x6e\x2e\x7e\x96\xe3\x41\xc2\x4e\xe3\x7c\x51\x00\x90\x56\x7b\xb4\xe5\x8e\x96\x61\x7e\x07\x00\x00\xff\xff\x29\x4c\x02\xa8\xcd\x00\x00\x00")

func templatesTmuxpConfigYamlBytes() ([]byte, error) {
	return bindataRead(
		_templatesTmuxpConfigYaml,
		"templates/tmuxp-config.yaml",
	)
}

func templatesTmuxpConfigYaml() (*asset, error) {
	bytes, err := templatesTmuxpConfigYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/tmuxp-config.yaml", size: 205, mode: os.FileMode(420), modTime: time.Unix(1540657347, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"templates/tmuxp-config-template.go": templatesTmuxpConfigTemplateGo,
	"templates/tmuxp-config.yaml":        templatesTmuxpConfigYaml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"templates": &bintree{nil, map[string]*bintree{
		"tmuxp-config-template.go": &bintree{templatesTmuxpConfigTemplateGo, map[string]*bintree{}},
		"tmuxp-config.yaml":        &bintree{templatesTmuxpConfigYaml, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
