environment:
  KUBECONFIG: {{ .KubeConfig -}}
{{- range $key, $value := .ExtraEnvs }}
  {{ $key }}: {{ $value -}}
{{ end }}

session_name: {{ .SessionName }}
windows:
  - panes: []
    window_name: default