// Code generated by go-bindata. (@generated) DO NOT EDIT.
// sources:
// templates/tmuxp-config-template.go
// templates/tmuxp-config.yaml
package templates

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _templatesTmuxpConfigTemplateGo = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x01\x00\x00\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00")

func templatesTmuxpConfigTemplateGoBytes() ([]byte, error) {
	return bindataRead(
		_templatesTmuxpConfigTemplateGo,
		"templates/tmuxp-config-template.go",
	)
}

func templatesTmuxpConfigTemplateGo() (*asset, error) {
	bytes, err := templatesTmuxpConfigTemplateGoBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/tmuxp-config-template.go", size: 0, mode: os.FileMode(420), modTime: time.Unix(1540655782, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _templatesTmuxpConfigYaml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x4a\xcd\x2b\xcb\x2c\xca\xcf\xcb\x4d\xcd\x2b\xb1\xe2\x52\x50\xf0\x0e\x75\x72\x75\xf6\xf7\x73\xf3\x74\xb7\x52\xa8\xae\x56\xd0\xf3\x2e\x4d\x4a\x75\xce\xcf\x4b\xcb\x4c\x57\xa8\xad\xe5\xe2\x2a\x4e\x2d\x2e\xce\xcc\xcf\x8b\xcf\x4b\xcc\x4d\x85\x28\x08\x86\x88\xf8\x25\xe6\xa6\x82\x54\x94\x67\xe6\xa5\xe4\x97\x17\x83\x8c\xd2\x55\x28\x48\xcc\x4b\x2d\xb6\x52\x88\x8e\xe5\x52\x50\x50\x50\x80\x48\x41\xb5\xa6\xa4\xa6\x25\x96\xe6\x94\x00\x02\x00\x00\xff\xff\x00\x4b\x38\xc6\x7e\x00\x00\x00")

func templatesTmuxpConfigYamlBytes() ([]byte, error) {
	return bindataRead(
		_templatesTmuxpConfigYaml,
		"templates/tmuxp-config.yaml",
	)
}

func templatesTmuxpConfigYaml() (*asset, error) {
	bytes, err := templatesTmuxpConfigYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "templates/tmuxp-config.yaml", size: 126, mode: os.FileMode(420), modTime: time.Unix(1540655763, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"templates/tmuxp-config-template.go": templatesTmuxpConfigTemplateGo,
	"templates/tmuxp-config.yaml":        templatesTmuxpConfigYaml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"templates": &bintree{nil, map[string]*bintree{
		"tmuxp-config-template.go": &bintree{templatesTmuxpConfigTemplateGo, map[string]*bintree{}},
		"tmuxp-config.yaml":        &bintree{templatesTmuxpConfigYaml, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
